config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord

  # Relations
  has_many :meals, through: :food_meals
  has_many :food_meals, foreign_key: "food_id", dependent: :destroy

  # Validations
  validates :name, presence: true, uniqueness: {case_sensitive: true},
                   length: {maximum:50}
  validates :calorie, presence: true, numericality: {only_integer: true}
  validates :group, presence: true, length: {maximum:50}
end

app/models/food_meal.rb
class FoodMeal < ApplicationRecord

  # Relations
  belongs_to :food
  belongs_to :meal

  # Validations
  validates :food_id, presence: true
  validates :meal_id, presence: true
end

app/models/meal.rb
class Meal < ApplicationRecord

  # Relations
  belongs_to :user
  has_many :foods, through: :food_meals
  has_many :food_meals, foreign_key: "meal_id", dependent: :destroy

  # Scope
  default_scope -> {order(date: :desc)}

  # Validates
  validates :user_id, presence: true
  validates :date, presence: true
  validate :date_cannot_be_in_the_future
  validates :meal_type, presence: true, inclusion: {in: %w(breakfast lunch dinner)}

  # Get total calorie of the meal
  def total_calorie
    sum = 0
    food_meals.each do |food_meal|
      sum += food_meal.food.calorie
    end
    return sum
  end

  # Add food to the meal
  def add_food(food)
    food_meals.create(food_id: food.id)
  end

  private

    # Check whether date is in the future
    def date_cannot_be_in_the_future
      if date > Date.today
        errors.add(:date, "You can't have meal in the future now...")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord

  # Relations
  has_many :meals, dependent: :destroy

  # Validations
  validates :name, presence: true, length: {maximum:50}, uniqueness: true
  validates :height, presence:true, numericality: {greater_than: 0.50,
                                                   less_than_or_equal_to: 3.00 }
  validates :weight, presence:true, numericality: {only_integer: true,
                                                   greater_than: 10,
                                                   less_than_or_equal_to: 1000 }
  validates :date_of_birth, presence:true
  validate :date_of_birth_cannot_be_in_the_future
  validates :strength, presence:true,
             numericality: {only_integer: true,
                            greater_than_or_equal_to: 1,
                            less_than_or_equal_to: 3}
  validates :sex, presence:true, inclusion: {in: %w(male female)}
  has_secure_password
  # add allow nil cause has_secure_password can detect nil
  validates :password, presence:true, length: {minimum:8}, allow_nil:true

  # Return body math index(BMI)
  def body_math_index
    weight / (height * height)
  end

  # Return standard weight
  def standard_weight
    if sex == "male"
      # male
      height * height * 22
    else
      # female
      height * height * 21
    end
  end

  # Return basal metabolic rate(BMR)
  def basal_metabolic_rate(age)
    if sex == "male"
      # male
      male_BMR(age)
    else
      # female
      female_BMR(age)
    end
  end

  # Return daily caloric requirement
  def caloric_requirement
    age = current_age
    bmr = basal_metabolic_rate(age)
    if strength == 1
      caloric_requirement_st1(age, bmr).to_i
    elsif strength == 2
      caloric_requirement_st2(age, bmr).to_i
    else
      caloric_requirement_st3(age, bmr).to_i
    end
  end

  def all_meals
    Meal.where(user_id: id)
  end

  def meal_of(date, meal_type)
    Meal.where(user_id: id).where(date: date).where(meal_type: meal_type)
  end

  private

    # Check whether date of birth is in the future
    def date_of_birth_cannot_be_in_the_future
      if date_of_birth > Date.today
        errors.add(:date_of_birth, "You cannot be born in the future...")
      end
    end

    # Return current age
    def current_age
      date_format = "%Y%m%d"
      (Date.today.strftime(date_format).to_i - date_of_birth.strftime(date_format).to_i) / 10000
    end

    # Return male BMR
    def male_BMR(age)
      case age
      when 0..14
        weight * 31.0
      when 15..17
        weight * 27.0
      when 18..29
        weight * 24.0
      when 30..49
        weight * 22.3
      else
        weight * 21.5
      end
    end

    # Return femal BMR
    def female_BMR(age)
      case age
      when 0..14
        weight * 29.6
      when 15..17
        weight * 25.3
      when 18..29
        weight * 22.1
      when 30..49
        weight * 21.7
      else
        weight * 20.7
      end
    end

    # Return caloric requirement(strength level1)
    def caloric_requirement_st1(age, bmr)
      case age
      when 0..14
        bmr * 1.45
      when 15..17
        bmr * 1.55
      when 18..69
        bmr * 1.50
      else
        bmr * 1.45
      end
    end

    # Return caloric requirement(strength level2)
    def caloric_requirement_st2(age, bmr)
      case age
      when 0..14
        bmr * 1.65
      when 15..17
        bmr * 1.75
      when 18..69
        bmr * 1.75
      else
        bmr * 1.70
      end
    end

    # Return caloric requirement(strength level3)
    def caloric_requirement_st3(age, bmr)
      case age
      when 0..14
        bmr * 1.85
      when 15..17
        bmr * 1.95
      when 18..69
        bmr * 2.00
      else
        bmr * 1.95
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Let's get healthy!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :date_of_birth, :sex, :height, :weight,
                                   :strength, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Calorie Checker", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
<%
=begin
%>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
<%
=end
%>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development?%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about">
  <div class="backgroundImage">
  </div>
  <div class="wrapper">
    <div class="main">
      <h1>About</h1>
      <p>
        Preparing...
      </p>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="contact">
  <div class="backgroundImage">
  </div>
  <div class="wrapper">
    <div class="main">
      <h1>Contact</h1>
      <p>
        Preparing...
      </p>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="help">
  <div class="backgroundImage">
  </div>
  <div class="wrapper">
    <div class="main">
      <h1>Help</h1>
      <p>
        Preparing...
      </p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Calorie Checker") %>
<div class="jumbotron">
  <h1>Calorie Checker</h1>
  <p>It's important to know how much calorie you can take and what you should eat. </p>
  <div class="button_wrapper">
      <%= link_to "Sign up here!", signup_path, class:"btn btn-lg btn-primary" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>
<div calss="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render  'shared/error_messages'%>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :date_of_birth %><br>
      <%= f.date_select :date_of_birth,
                        {
                          order: [:day, :month, :year],
                          start_year: 1900,
                          end_year: Date.today.year,
                          default: Date.new(2000, 1, 1)
                        },
                        {class: 'form-control bootstrap-date'} %><br>

      <p class="form-label">Sex</p>
      <label class="radio-inline">
        <%= f.radio_button :sex, "male", {checked: true} %>male
      </label>
      <label class="radio-inline">
        <%= f.radio_button :sex, "female" %>female
      </label><br>

      <%= f.label :height, "Height(m)" %>
      <%= f.number_field :height, in: 0.50..3.00, step: 0.01,
                                  class: 'number_form form-control' %>

      <%= f.label :weight, "Weight(kg)" %>
      <%= f.number_field :weight, in: 10..1000, step: 1,
                                  class: 'number_form form-control' %>

      <%= f.label :strength %>
      <%= f.select :strength, [1,2,3], {}, {class: 'number_form form-control'} %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.submit "Create new account", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>